export const REDIS_CHANNELS = {
  EXITO_CORREO_TICKET: 'successCorreoTicket',
  ERROR_CORREO_TICKET: 'errorCorreo',
  GENERICO: 'genericLog',
  EXITO_CORREO_CONTACTO: 'successCorreoContacto',
  ERROR_CORREO_CONTACTO: 'errorContacto',
  EXITO_CORREO_PENDIENTE: 'successPendiente',
  ERROR_CORREO_PENDIENTE: 'errorPendiente',
  USUARIO_CREADO: 'usuarioCreado',
  USUARIO_NO_CREADO: 'usuarioNoCreado',
  USUARIO_ACTUALIZADO: 'usuarioactualizado',
  USUARIO_NO_ACTUALIZADO: 'usuarioNoactualizado',
  ESTADO_ACTUALIZADO: 'estadoActualizado',
  ESTADO_NO_ACTUALIZADO: 'estadoNoActualizado',
  CLIENTE_CREADO: 'clienteCreado',
  CLIENTE_NO_CREADO: 'clienteNoCreado',
  CLIENTE_ACTUALIZADO: 'clienteActualizado',
  CLIENTE_NO_ACTUALIZADO: 'clienteNoActualizado',
};
